### ISSUE TITLE
$refs path problem

### ISSUE THREAD

**Issue by devarda** [wikimedia/jsonschema-tools#15]
Hello,

I used [openapi2jsonschema](https://github.com/instrumenta/openapi2jsonschema) to convert swagger.json to a bunch of models and definitions in JSON schema. Then used jsonschema-tools to dereference an api endpoint schema to get a single file. As I was doing that I ran into an issue of (wrongly) stacked directory paths for reference.

The problem is that the endpoint schema reference looks like:

```
 "PersonInfo": {
      "$ref": "_definitions.json#/definitions/Person",
    },
```

The `_definitions.json` that has the definition also has a reference and the model:

```
definitions: {
... 
"PersonInfo": {
          "$ref": "#/definitions/Person",
          "description": "Information about the primary consumer"
        },
   "Person": {
      "type": "object",
      "properties": {
...
```

Say that what I'm parsing is in `/absolute/dir/to-parse/endpoint.json`. In this case, after running `jsonschema-tools dereference /absolute/dir/to-parse/endpoint.json`, when it finds a reference it tries to look in: `/absolute/dir/to-parse/absolute/dir/to-parse/endpoint.json` and throws an opening file error.

I did a hack in lib/jsonschema-tools.js around line 300 to overcome this:

```
function resolveUri(uri, baseUri) {
    let url         = uri;
    // my hack, workaround
    let baseDir     = path.dirname(process.argv[3]);
    let refJson     = path.basename(uri);
    let refJsonPath = path.join(baseDir, refJson);
    if (fs.existsSync(refJsonPath)) {
        url = refJsonPath;
    } else {
        // If the uri doesn't have a protocol, then we can use
        // the given baseUri as the default.
        if (baseUri && !uriHasProtocol(url) && !fs.existsSync(url)) {
            url = baseUri + url;
        }
    }


    // If the url still doesn't have a protocol, assume it should be file://.
    if (!uriHasProtocol(url)) {
        url = `file://${path.resolve(url)}`;
    }
    return url;
}
```

I hope this helps identify a possible bug or someone else with the same issue.

**Comment by ottomata** [comment]
Hm, interesting.  jsonschema-tools is meant to manage a repository of JSONSchema files, and assumes that any non-in document $refs are resolvable via configured schema-base-uris. The default schema-base-uri is process.cwd.  Maybe its because you aren't executing jsonschema-tools from somewhere that _definitions.json is relative to process.cwd?  What happens if you try

```jsonschema-tools dereference --schema-base-uris /absolute/dir/to-parse```

?  (Assuming _definitions.json is at  /absolute/dir/to-parse/_definitions.json)

**Comment by ottomata** [comment]
Closing as stale.
