### ISSUE TITLE
Test for repository structure fails if `contentTypes: [json]`

### ISSUE THREAD

**Issue by bd808** [wikimedia/jsonschema-tools#21]
The logic in `findSchemaPaths` filters its results to match the defined contentTypes option. If 'yaml' is not included in this list then the `current.yaml` file will be excluded from the generated list. This in turn prevents `findAllSchemasInfo` from collecting information on current.yaml. Ultimately this causes a failure in tests/structure.js:

```
  Schema Repository Structure in ./jsonschema/
    Schema with title toolinfo
      1) must have a current.yaml file


  0 passing (8ms)
  1 failing

  1) Schema Repository Structure in ./jsonschema/
       Schema with title toolinfo
         must have a current.yaml file:

      AssertionError [ERR_ASSERTION]: could not find current schema file
      + expected - actual

      -false
      +true

      at Context.it.only (node_modules/@wikimedia/jsonschema-tools/lib/tests/structure.js:67:32)
```

My .jsonschema-tools.yaml:
```yaml
contentTypes: [json]
logLevel: info
schemaBasePath: ./jsonschema/
shouldDereference: false
shouldSymlinkExtensionless: true
shouldSymlinkLatest: false
```

My jsonschema directory:
```
$ ls -alhR jsonschema
total 0
drwxr-xr-x   3 bd808  staff    96B Sep 21 10:56 ./
drwxr-xr-x  26 bd808  staff   832B Sep 21 13:31 ../
drwxr-xr-x   6 bd808  staff   192B Sep 21 13:23 toolinfo/

jsonschema/toolinfo:
total 24
drwxr-xr-x  6 bd808  staff   192B Sep 21 13:23 ./
drwxr-xr-x  3 bd808  staff    96B Sep 21 10:56 ../
lrwxrwxrwx  1 bd808  staff    10B Sep 21 11:58 1.0.0@ -> 1.0.0.json
-rw-r--r--  1 bd808  staff   1.1K Sep 21 11:58 1.0.0.json
-rw-r--r--  1 bd808  staff   145B Sep 21 12:04 CHANGELOG.rst
-rw-r--r--  1 bd808  staff   769B Sep 21 13:23 current.yaml
```

**Comment by bd808** [comment]
The `materialize-all` command also fails to find anything to do when contentTypes does not include 'yaml' for functionally the same reason (current.yaml excluded from the list of known schema files in the repo).

If I comment out this line in `findSchemaPaths`:
```
.filter(p => options.contentTypes.includes(p.ext.slice(1)))
```
then both the test suite and `jsonschema-tools materialize-all` start working as expected.

**Comment by ottomata** [comment]
Interesting!  Def a bug.  What if you add

```
currentName: current.json
```
And make your current file be in JSON format instead?

**Comment by bd808** [comment]
> What if you add
> ```
> currentName: current.json
> ```
> And make your current file be in JSON format instead?

That makes things work too. I guess I just want the best of all worlds: yaml for the "master" document, but only json output for end users.

The surprising behavior here to an end-user is the undocumented interaction of contentTypes and currentName. At minimum I'd like to see a note added in the config file documentation stating that the extension used for currentName **must** be included in contentTypes or things will get confused.

**Comment by ottomata** [comment]
Indeed!  Ah sorry I think my github notifications are filtered weird, sorry I didn't see this before.  This indeed should be fixed.
